apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  my-realm.json: |
    {
      "realm": "myrealm",
      "enabled": true,
      "users": [
        {
          "username": "myuser",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "mypassword"
            }
          ]
        }
      ]
    }
  keycloak-entrypoint.sh: |
    #!/bin/bash

    # Ensure all necessary environment variables are set
    : "${KEYCLOAK_USER:?KEYCLOAK_USER environment variable is required}"
    : "${KEYCLOAK_PASSWORD:?KEYCLOAK_PASSWORD environment variable is required}"
    : "${DB_VENDOR:?DB_VENDOR environment variable is required}"
    : "${DB_ADDR:?DB_ADDR environment variable is required}"
    : "${DB_DATABASE:?DB_DATABASE environment variable is required}"
    : "${DB_USER:?DB_USER environment variable is required}"
    : "${DB_PASSWORD:?DB_PASSWORD environment variable is required}"

    # Start Keycloak in development mode (change as necessary)
    /opt/keycloak/bin/kc.sh start-dev --import-realm

    # If any additional custom commands or initialization is required, include them here
