apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  KEYCLOAK_USER: YWRtaW4=
  KEYCLOAK_PASSWORD: YWRtaW4xMjM0NQ==
  DB_VENDOR: UE9TVEdSRVM=
  DB_ADDR: cG9zdGdyZXM=
  DB_DATABASE: dHJpcF9kYg==
  DB_USER: YWRtaW4=
  DB_PASSWORD: YWRtaW4xMjM0NQ==
