apiVersion: v1
kind: Pod
metadata:
  name: keycloak
spec:
  containers:
    - name: keycloak
      image: jboss/keycloak:latest
      volumeMounts:
        - name: keycloak-entrypoint
          mountPath: /opt/jboss/tools/keycloak-entrypoint.sh
          subPath: keycloak-entrypoint.sh
          readOnly: true
  volumes:
    - name: keycloak-entrypoint
      configMap:
        name: keycloak-entrypoint
        items:
          - key: keycloak-entrypoint.sh
            path: keycloak-entrypoint.sh
