apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:latest
          volumeMounts:
            - name: keycloak-entrypoint
              mountPath: /opt/jboss/tools/keycloak-entrypoint.sh
              subPath: keycloak-entrypoint.sh
              readOnly: true
      volumes:
        - name: keycloak-entrypoint
          configMap:
            name: keycloak-entrypoint
            items:
              - key: keycloak-entrypoint.sh
                path: keycloak-entrypoint.sh
