apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  postgres-entrypoint.sh: |
    #!/bin/bash
    # Ensure all necessary environment variables are set
    : "${POSTGRES_USER:?POSTGRES_USER environment variable is required}"
    : "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD environment variable is required}"
    : "${POSTGRES_DB:?POSTGRES_DB environment variable is required}"
    : "${PGADMIN_DEFAULT_EMAIL:?PGADMIN_DEFAULT_EMAIL environment variable is required}"
    : "${PGADMIN_DEFAULT_PASSWORD:?PGADMIN_DEFAULT_PASSWORD environment variable is required}"
