apiVersion: v1
kind: Secret
metadata:
  name: env-config
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4xMjM0NQ==
  POSTGRES_DB: dHJpcF9kYg==
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AdHJpcC5jb20=
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4xMjM0NQ==
