#!/bin/bash

# Set necessary environment variables
export  POSTGRES_USER=${POSTGRES_USER}
export  POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
export  POSTGRES_DB=${POSTGRES_DB}
export  PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
export  PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
